// data.js
export const playersData = {
    mostRuns: [
      {
        rank: 1,
        name: "Virat Kohli",
        team: "India",
        runs: 1420,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 2,
        name: "Steve Smith",
        team: "Australia",
        runs: 1340,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 3,
        name: "Joe Root",
        team: "England",
        runs: 1270,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 4,
        name: "Kane Williamson",
        team: "New Zealand",
        runs: 1230,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 5,
        name: "Babar Azam",
        team: "Pakistan",
        runs: 1190,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 6,
        name: "David Warner",
        team: "Australia",
        runs: 1150,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 7,
        name: "Rohit Sharma",
        team: "India",
        runs: 1120,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 8,
        name: "Quinton de Kock",
        team: "South Africa",
        runs: 1100,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 9,
        name: "Aaron Finch",
        team: "Australia",
        runs: 1080,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 10,
        name: "Eoin Morgan",
        team: "England",
        runs: 1050,
        avatar: "https://via.placeholder.com/150",
      },
    ],
    mostBoundaries: [
      {
        rank: 1,
        name: "AB de Villiers",
        team: "South Africa",
        boundaries: 420,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 2,
        name: "Chris Gayle",
        team: "West Indies",
        boundaries: 400,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 3,
        name: "Sachin Tendulkar",
        team: "India",
        boundaries: 380,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 4,
        name: "Rohit Sharma",
        team: "India",
        boundaries: 370,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 5,
        name: "David Warner",
        team: "Australia",
        boundaries: 360,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 6,
        name: "Virat Kohli",
        team: "India",
        boundaries: 350,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 7,
        name: "Kane Williamson",
        team: "New Zealand",
        boundaries: 340,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 8,
        name: "Aaron Finch",
        team: "Australia",
        boundaries: 330,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 9,
        name: "Shikhar Dhawan",
        team: "India",
        boundaries: 320,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 10,
        name: "Fakhar Zaman",
        team: "Pakistan",
        boundaries: 310,
        avatar: "https://via.placeholder.com/150",
      },
    ],
    mostFifties: [
      {
        rank: 1,
        name: "Ricky Ponting",
        team: "Australia",
        fifties: 50,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 2,
        name: "Jacques Kallis",
        team: "South Africa",
        fifties: 48,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 3,
        name: "Inzamam-ul-Haq",
        team: "Pakistan",
        fifties: 46,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 4,
        name: "Sachin Tendulkar",
        team: "India",
        fifties: 45,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 5,
        name: "Mahela Jayawardene",
        team: "Sri Lanka",
        fifties: 44,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 6,
        name: "Virat Kohli",
        team: "India",
        fifties: 42,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 7,
        name: "Rohit Sharma",
        team: "India",
        fifties: 41,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 8,
        name: "Hashim Amla",
        team: "South Africa",
        fifties: 40,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 9,
        name: "David Warner",
        team: "Australia",
        fifties: 39,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 10,
        name: "Chris Gayle",
        team: "West Indies",
        fifties: 38,
        avatar: "https://via.placeholder.com/150",
      },
    ],
    mostHundreds: [
      {
        rank: 1,
        name: "Sachin Tendulkar",
        team: "India",
        hundreds: 49,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 2,
        name: "Ricky Ponting",
        team: "Australia",
        hundreds: 30,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 3,
        name: "Virat Kohli",
        team: "India",
        hundreds: 27,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 4,
        name: "Rohit Sharma",
        team: "India",
        hundreds: 26,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 5,
        name: "David Warner",
        team: "Australia",
        hundreds: 25,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 6,
        name: "Kumar Sangakkara",
        team: "Sri Lanka",
        hundreds: 24,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 7,
        name: "Shikhar Dhawan",
        team: "India",
        hundreds: 23,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 8,
        name: "Hashim Amla",
        team: "South Africa",
        hundreds: 22,
        avatar: "https://via.placeholder.com/150",
      },
      { rank: 9, name: "Chris Gayle", team: "West Indies", hundreds: 21 },
      {
        rank: 9,
        name: "Chris Gayle",
        team: "West Indies",
        hundreds: 21,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 10,
        name: "AB de Villiers",
        team: "South Africa",
        hundreds: 20,
        avatar: "https://via.placeholder.com/150",
      },
    ],
    mostFours: [
      {
        rank: 1,
        name: "Sachin Tendulkar",
        team: "India",
        fours: 2000,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 2,
        name: "Kumar Sangakkara",
        team: "Sri Lanka",
        fours: 1800,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 3,
        name: "Adam Gilchrist",
        team: "Australia",
        fours: 1600,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 4,
        name: "Virat Kohli",
        team: "India",
        fours: 1500,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 5,
        name: "Ricky Ponting",
        team: "Australia",
        fours: 1400,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 6,
        name: "Jacques Kallis",
        team: "South Africa",
        fours: 1300,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 7,
        name: "Sourav Ganguly",
        team: "India",
        fours: 1200,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 8,
        name: "Brian Lara",
        team: "West Indies",
        fours: 1100,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 9,
        name: "Rohit Sharma",
        team: "India",
        fours: 1000,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 10,
        name: "Sanath Jayasuriya",
        team: "Sri Lanka",
        fours: 900,
        avatar: "https://via.placeholder.com/150",
      },
    ],
    mostSixes: [
      {
        rank: 1,
        name: "Shahid Afridi",
        team: "Pakistan",
        sixes: 351,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 2,
        name: "Chris Gayle",
        team: "West Indies",
        sixes: 330,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 3,
        name: "Sanath Jayasuriya",
        team: "Sri Lanka",
        sixes: 270,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 4,
        name: "Rohit Sharma",
        team: "India",
        sixes: 250,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 5,
        name: "MS Dhoni",
        team: "India",
        sixes: 240,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 6,
        name: "AB de Villiers",
        team: "South Africa",
        sixes: 230,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 7,
        name: "Brendon McCullum",
        team: "New Zealand",
        sixes: 220,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 8,
        name: "Adam Gilchrist",
        team: "Australia",
        sixes: 210,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 9,
        name: "Virender Sehwag",
        team: "India",
        sixes: 200,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 10,
        name: "Eoin Morgan",
        team: "England",
        sixes: 190,
        avatar: "https://via.placeholder.com/150",
      },
    ],
    fastestFifties: [
      {
        rank: 1,
        name: "Yuvraj Singh",
        team: "India",
        time: "12 balls",
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 2,
        name: "AB de Villiers",
        team: "South Africa",
        time: "14 balls",
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 3,
        name: "Chris Gayle",
        team: "West Indies",
        time: "16 balls",
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 4,
        name: "Sanath Jayasuriya",
        team: "Sri Lanka",
        time: "17 balls",
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 5,
        name: "Shahid Afridi",
        team: "Pakistan",
        time: "17 balls",
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 6,
        name: "Corey Anderson",
        team: "New Zealand",
        time: "18 balls",
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 7,
        name: "Virat Kohli",
        team: "India",
        time: "18 balls",
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 8,
        name: "Adam Gilchrist",
        team: "Australia",
        time: "19 balls",
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 9,
        name: "Brendon McCullum",
        team: "New Zealand",
        time: "20 balls",
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 10,
        name: "Virender Sehwag",
        team: "India",
        time: "20 balls",
        avatar: "https://via.placeholder.com/150",
      },
    ],
    fastestHundreds: [
      {
        rank: 1,
        name: "AB de Villiers",
        team: "South Africa",
        time: "31 balls",
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 2,
        name: "Corey Anderson",
        team: "New Zealand",
        time: "36 balls",
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 3,
        name: "Shahid Afridi",
        team: "Pakistan",
        time: "37 balls",
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 4,
        name: "Mark Boucher",
        team: "South Africa",
        time: "44 balls",
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 5,
        name: "Brian Lara",
        team: "West Indies",
        time: "45 balls",
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 6,
        name: "Shahid Afridi",
        team: "Pakistan",
        time: "45 balls",
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 7,
        name: "Brian Lara",
        team: "West Indies",
        time: "45 balls",
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 8,
        name: "AB de Villiers",
        team: "South Africa",
        time: "46 balls",
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 9,
        name: "Virender Sehwag",
        team: "India",
        time: "46 balls",
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 10,
        name: "Shahid Afridi",
        team: "Pakistan",
        time: "47 balls",
        avatar: "https://via.placeholder.com/150",
      },
    ],
  
    // Add more categories with 10 entities each...
  };
 export const bowlersData = {
    highestWickets: [
      {
        rank: 1,
        name: "M.Muralitharan",
        team: "Sri Lanka",
        wickets: 1347,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 2,
        name: "Shane Warne",
        team: "Australia",
        wickets: 1001,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 3,
        name: "Anil Kumble",
        team: "India",
        wickets: 956,
        avatar: "https://via.placeholder.com/150",
      },
      // Add more players...
      {
        rank: 4,
        name: "James Anderson",
        team: "England",
        wickets: 614,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 5,
        name: "Glenn McGrath",
        team: "Australia",
        wickets: 563,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 6,
        name: "Courtney Walsh",
        team: "West Indies",
        wickets: 519,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 7,
        name: "Kapil Dev",
        team: "India",
        wickets: 434,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 8,
        name: "Imran Khan",
        team: "Pakistan",
        wickets: 362,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 9,
        name: "Wasim Akram",
        team: "Pakistan",
        wickets: 414,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 10,
        name: "Curtly Ambrose",
        team: "West Indies",
        wickets: 405,
        avatar: "https://via.placeholder.com/150",
      },
    ],
    most5WicketHauls: [
      {
        rank: 1,
        name: "Muttiah Muralitharan",
        team: "Sri Lanka",
        hauls: 67,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 2,
        name: "Richard Hadlee",
        team: "New Zealand",
        hauls: 36,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 3,
        name: "Anil Kumble",
        team: "India",
        hauls: 35,
        avatar: "https://via.placeholder.com/150",
      },
      // Add more players...
      {
        rank: 4,
        name: "Shane Warne",
        team: "Australia",
        hauls: 29,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 5,
        name: "James Anderson",
        team: "England",
        hauls: 27,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 6,
        name: "Wasim Akram",
        team: "Pakistan",
        hauls: 25,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 7,
        name: "Glenn McGrath",
        team: "Australia",
        hauls: 29,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 8,
        name: "Curtly Ambrose",
        team: "West Indies",
        hauls: 22,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 9,
        name: "Courtney Walsh",
        team: "West Indies",
        hauls: 22,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 10,
        name: "Shaun Pollock",
        team: "South Africa",
        hauls: 20,
        avatar: "https://via.placeholder.com/150",
      },
    ],
    fastest50Wickets: [
      {
        rank: 1,
        name: "Ajantha Mendis",
        team: "Sri Lanka",
        time: "19 M",
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 2,
        name: "George Lohmann",
        team: "England",
        time: "16 matches",
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 3,
        name: "Charles Turner",
        team: "Australia",
        time: "15 matches",
        avatar: "https://via.placeholder.com/150",
      },
      // Add more players...
      {
        rank: 4,
        name: "Ravichandran Ashwin",
        team: "India",
        time: "23 matches",
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 5,
        name: "Dennis Lillee",
        team: "Australia",
        time: "24 matches",
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 6,
        name: "Mitchell Starc",
        team: "Australia",
        time: "26 matches",
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 7,
        name: "Saqlain Mushtaq",
        team: "    Pakistan",
        time: "26 matches",
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 8,
        name: "Waqar Younis",
        team: "Pakistan",
        time: "27 matches",
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 9,
        name: "Dale Steyn",
        team: "South Africa",
        time: "27 matches",
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 10,
        name: "Dennis Lillee",
        team: "Australia",
        time: "28 matches",
        avatar: "https://via.placeholder.com/150",
      },
    ],
    bestSpell: [
      {
        rank: 1,
        name: "Jim Laker",
        team: "England",
        wickets: 10,
        runs: "3/5W",
        against: "Australia",
        venue: "Old Trafford",
        date: "1956",
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 2,
        name: "Anil Kumble",
        team: "India",
        wickets: 10,
        runs: "4/10W",
        against: "Pakistan",
        venue: "Feroz Shah Kotla",
        date: "1999",
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 3,
        name: "Bob Massie",
        team: "Australia",
        wickets: 16,
        runs: 137,
        against: "England",
        venue: "Lord's",
        date: "1972",
        avatar: "https://via.placeholder.com/150",
      },
      // Add more players...
      {
        rank: 4,
        name: "Richard Hadlee",
        team: "New Zealand",
        wickets: 9,
        runs: 52,
        against: "Australia",
        venue: "Brisbane",
        date: "1985",
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 5,
        name: "Lance Klusener",
        team: "South Africa",
        wickets: 8,
        runs: 64,
        against: "India",
        venue: "Eden Gardens",
        date: "1996",
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 6,
        name: "Jim Laker",
        team: "England",
        wickets: 10,
        runs: 88,
        against: "Australia",
        venue: "Old Trafford",
        date: "1956",
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 7,
        name: "Monty Panesar",
        team: "England",
        wickets: 6,
        runs: 37,
        against: "India",
        venue: "Wankhede Stadium",
        date: "2012",
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 8,
        name: "Devon Malcolm",
        team: "England",
        wickets: 9,
        runs: 57,
        against: "South Africa",
        venue: "The Oval",
        date: "1994",
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 9,
        name: "Jim Laker",
        team: "England",
        wickets: 10,
        runs: 53,
        against: "Australia",
        venue: "Old Trafford",
        date: "1956",
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 10,
        name: "Tom Richardson",
        team: "England",
        wickets: 6,
        runs: 39,
        against: "Australia",
        venue: "Sydney Cricket Ground",
        date: "1894",
        avatar: "https://via.placeholder.com/150",
      },
    ],
  };
  
 export const moreData = {
    bestAllRounder: [
      {
        rank: 1,
        name: "Jacques Kallis",
        team: "South Africa",
        runs: 13289,
        wickets: 577,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 2,
        name: "Shaun Pollock",
        team: "South Africa",
        runs: 3781,
        wickets: 829,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 3,
        name: "Imran Khan",
        team: "Pakistan",
        runs: 3807,
        wickets: 757,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 4,
        name: "Richard Hadlee",
        team: "New Zealand",
        runs: 3124,
        wickets: 589,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 5,
        name: "Kapil Dev",
        team: "India",
        runs: 5248,
        wickets: 687,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 6,
        name: "Ian Botham",
        team: "England",
        runs: 5200,
        wickets: 528,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 7,
        name: "Shakib Al Hasan",
        team: "Bangladesh",
        runs: 6331,
        wickets: 632,
        avatar: "https://via.placeholder.com/150",
      },
    ],
    mostCatches: [
      {
        rank: 1,
        name: "Mahela Jayawardene",
        team: "Sri Lanka",
        catches: 205,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 2,
        name: "Ricky Ponting",
        team: "Australia",
        catches: 196,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 3,
        name: "Jacques Kallis",
        team: "South Africa",
        catches: 200,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 4,
        name: "AB de Villiers",
        team: "South Africa",
        catches: 192,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 5,
        name: "Stephen Fleming",
        team: "New Zealand",
        catches: 171,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 6,
        name: "Kumar Sangakkara",
        team: "Sri Lanka",
        catches: 206,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 7,
        name: "Ross Taylor",
        team: "New Zealand",
        catches: 166,
        avatar: "https://via.placeholder.com/150",
      },
    ],
    mostRunOuts: [
      {
        rank: 1,
        name: "Jonty Rhodes",
        team: "South Africa",
        runOuts: 60,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 2,
        name: "Mohammad Kaif",
        team: "India",
        runOuts: 41,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 3,
        name: "Paul Collingwood",
        team: "England",
        runOuts: 40,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 4,
        name: "Suresh Raina",
        team: "India",
        runOuts: 38,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 5,
        name: "Ricky Ponting",
        team: "Australia",
        runOuts: 37,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 6,
        name: "AB de Villiers",
        team: "South Africa",
        runOuts: 36,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 7,
        name: "Virat Kohli",
        team: "India",
        runOuts: 34,
        avatar: "https://via.placeholder.com/150",
      },
    ],
    playerOfTheSeason: [
      {
        season: "2023",
        name: "Virat Kohli",
        team: "India",
        avatar: "https://via.placeholder.com/150",
      },
      {
        season: "2022",
        name: "Kane Williamson",
        team: "New Zealand",
        avatar: "https://via.placeholder.com/150",
      },
      {
        season: "2021",
        name: "Joe Root",
        team: "England",
        avatar: "https://via.placeholder.com/150",
      },
      {
        season: "2020",
        name: "Steven Smith",
        team: "Australia",
        avatar: "https://via.placeholder.com/150",
      },
      {
        season: "2019",
        name: "Rohit Sharma",
        team: "India",
        avatar: "https://via.placeholder.com/150",
      },
      {
        season: "2018",
        name: "Virat Kohli",
        team: "India",
        avatar: "https://via.placeholder.com/150",
      },
      {
        season: "2017",
        name: "Steve Smith",
        team: "Australia",
        avatar: "https://via.placeholder.com/150",
      },
    ],
    mostDucks: [
      {
        rank: 1,
        name: "Sanath Jayasuriya",
        team: "Sri Lanka",
        ducks: 34,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 2,
        name: "Sachin Tendulkar",
        team: "India",
        ducks: 20,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 3,
        name: "Inzamam-ul-Haq",
        team: "Pakistan",
        ducks: 26,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 4,
        name: "Rahul Dravid",
        team: "India",
        ducks: 14,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 5,
        name: "Adam Gilchrist",
        team: "Australia",
        ducks: 23,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 5,
        name: "Ricky Ponting",
        team: "Australia",
        ducks: 22,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 6,
        name: "Jacques Kallis",
        team: "South Africa",
        ducks: 18,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 7,
        name: "Kumar Sangakkara",
        team: "Sri Lanka",
        ducks: 17,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 8,
        name: "Brian Lara",
        team: "West Indies",
        ducks: 16,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 9,
        name: "Chris Gayle",
        team: "West Indies",
        ducks: 15,
        avatar: "https://via.placeholder.com/150",
      },
      {
        rank: 10,
        name: "Shivnarine Chanderpaul",
        team: "West Indies",
        ducks: 14,
        avatar: "https://via.placeholder.com/150",
      },
    ],
  };
  
  